### ISSUE TITLE
Add .gitattributes to project with proper info

### ISSUE THREAD

**Issue by yurii-polishchuk** [yurii-polishchuk/project-trainee-java#10]
text, binary and EOF info
- https://medium.com/@pablorsk/be-a-git-ninja-the-gitattributes-file-e58c07c9e915

**Comment by ihormedvid** [comment]
Не дуже впевний що так.
Але я правильно зрозумів суть його:
gitattributes - його задача,визначити які файли є тесктові,а які ні(бінарні).
Тобто він явно каже,коли текстовий,а коли ні.

**Comment by yurii-polishchuk** [comment]
sort of.

https://www.quora.com/What-is-a-“gitattribute”-in-terms-of-GitHub-and-version-control
