### ISSUE TITLE
Create Basic Java-project skeleton

### ISSUE THREAD

**Issue by yurii-polishchuk** [yurii-polishchuk/project-trainee-java#2]
**Requirements**
- Create basic folder structure. Please follow guides: https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html
- Add Maven
- Ad basic Main class with main method. 

**Result**
 - Application should run in console. (print Hello World for example)
 - application should run via IDEA and Maven
 - Pull Request with update

**Comment by ihormedvid** [comment]
https://github.com/ihormedvid/project-trainee-java/pull/2
