### ISSUE TITLE
Setup basic development environment

### ISSUE THREAD

**Issue by yurii-polishchuk** [yurii-polishchuk/project-trainee-java#3]
**Requirements**

# OS
* Windows / Linux / MacOS
* command-line (cmd, terminal, etc)

# IDE
* [IntelliJ IDEA Community Edition](https://www.jetbrains.com/idea/download/)

# Browsers
* [Google Chrome](https://www.google.com/chrome/browser/desktop/index.html) 

# BackEnd
## Programming Languages / SDK / etc.
* [Java v.11 (JDK and JRE)](https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html) or via [SDK Man](https://sdkman.io/install)

## Frameworks
* none for now

# Tools
* [Maven v.3](https://maven.apache.org/download.cgi) or via [SDK Man](https://sdkman.io/install)

**Result**
* setup-ed env
* please attach result of such command line output

1. java -version
2.mvn -version

**Comment by ihormedvid** [comment]
java -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)

 mvn -version
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.3, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-25-generic", arch: "amd64", family: "unix"
